title: skimit bluemap history
description: history maps of <a href="https://skimit.net/">skimit</a>, built using <a href="https://bluemap.bluecolored.de/">bluemap</a>
show_downloads: false
google_analytics: 
theme: jekyll-theme-cayman
